### ISSUE TITLE
new extra-cmake-modules breaks hawaii shell build

### ISSUE THREAD

**Issue by n3rdopolis** [hawaii-desktop/hawaii-shell#172]
I think it is due to commit http://quickgit.kde.org/?p=extra-cmake-modules.git&a=commit&h=807ace309a489d21163b5c671d9e449c06e14e20 and the fact that it adds the uninstall ablity, and now conflicts.

I get:
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Warning at /opt/share/ECM/kde-modules/KDEInstallDirs.cmake:586 (message):
  KDE_INSTALL_BINDIR, KDE_INSTALL_LIBDIR and KDE_INSTALL_INCLUDEDIR should
  either all be absolute paths or all be relative paths.
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)

Thanks

-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Failed
CMake Error at CMakeLists.txt:42 (add_custom_target):
  add_custom_target cannot create target "uninstall" because another target
  with the same name already exists.  The existing target is a custom target
  created in source directory "/srcbuild/hawaii-shell".  See documentation
  for policy CMP0002 for more details.

**Comment by plfiorini** [comment]
This should be fixed now, can you confirm?
If fixed I will do the same on greenisland

**Comment by n3rdopolis** [comment]
this affects system-preferences (and previously hawaii-shell), not greenisland.
However, I am unable to build hawaii shell, because now, greenisland is failing with 

[ 38%] [ 40%] [ 42%] [ 42%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/applicationmanager.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/clientwindow.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o
Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/globalregistry.cpp.o
[ 44%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/gldebug.cpp.o
[ 45%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/homeapplication.cpp.o
/srcbuild/greenisland/src/libgreenisland/compositor.cpp: In member function ‘virtual QWaylandSurfaceView* GreenIsland::Compositor::pickView(const QPointF&) const’:
/srcbuild/greenisland/src/libgreenisland/compositor.cpp:319:52: error: ‘class QWaylandOutput’ has no member named ‘surfaces’
             for (QWaylandSurface *surface: output->surfaces()) {
                                                    ^
src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:204: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o' failed
make[2]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/compositor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:425: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/all' failed
make[1]: *** [src/libgreenisland/CMakeFiles/GreenIsland.dir/all] Error 2
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
PackageCompileSource finished in 14 seconds

qtwayland is using the mainline dev branch, and was rebuilt.

and because greenisland is failing, I can't build hawaii-shell to confirm

**Comment by n3rdopolis** [comment]
It works! It just needs to be applied to hawaii-system-preferences too.

**Comment by lordsigma** [comment]
n3rdopolis, I have the same problem building greenisland from aur (archlinux) can you tell me how to fix this?

thanks in advance

**Comment by lordsigma** [comment]
how do I apply that to hawaii-shell?

**Comment by n3rdopolis** [comment]
This issue is fixed in hawaii-shell , and greenisland master... ...at least for me?

**Comment by lordsigma** [comment]
n3rdpolis. Reading better, my error is on the clientwindow.cpp.o and not onth ecompositor.cpp.o
still cannot build haiwaii-meta-git

**Comment by lordsigma** [comment]
this is the output of the error:

[ 33%] Building CXX object src/libgreenisland/CMakeFiles/GreenIsland.dir/clientw indow.cpp.o 
/tmp/yaourt-tmp-agustin/aur-greenisland-git/src/greenisland/src/libgreenisland/clientwindow.cpp:31:39: fatal error: QtCompositor/QWaylandClient: No such 
file or directory
 #include <QtCompositor/QWaylandClient>
compilation terminated. 
src/libgreenisland/CMakeFiles/GreenIsland.dir/build.make:208: recipe for target 'src/libgreenisland/CMakeFiles/GreenIsland.dir/clientwindow.cpp.o' failed make[2]: *** 
[src/libgreenisland/CMakeFiles/GreenIsland.dir/clientwindow.cpp.o] Error 1 CMakeFiles/Makefile2:428: recipe for target 'src/libgreenisland/CMakeFiles/Green Island.dir/all' failed make[1]: *** 
[src/libgreenisland/CMakeFiles/GreenIsland.dir/all] Error 2 
Makefile:147: recipe for target 'all' failed make: *** [all] Error 2 ==> 
ERROR: A failure occurred in build().
Aborting... ==> ERROR: Makepkg was unable to build greenisland-git. 
==> Restart building greenisland-git ? [y/N] ==>

**Comment by lordsigma** [comment]
Thanks for the help (none at all). I guess I will be uninstalling this from my arch and continue with LXDE, at least they answer the questions.

**Comment by plfiorini** [comment]
1. Just give time to people to read Github comments, you posted this just yesterday
2. You are adding comments to an already closed issue that has nothing to do with your problem. Please create a new one when the problem you are reporting is not the same.
3. You probably didn't install hawaii-qt5-wayland-git, please try installing that before building Hawaii.

Thanks.
